version: 2

jobs:
  publish:
    docker:
      - image: docker
    working_directory: ~/HaskellR
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t tweag/haskellr .
      - run:
          name: Publish Docker image
          command: |
            if [[ $CIRCLE_PROJECT_USERNAME = "tweag" ]];
            then
                echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                docker push tweag/haskellr
                docker tag tweag/haskellr tweag/haskellr:$CIRCLE_TAG
                docker push tweag/haskellr:$CIRCLE_TAG
            fi
  build-linux-nix:
    docker:
      - image: nixos/nix
    working_directory: ~/HaskellR
    steps:
      - checkout
      - run:
          name: Install Stack
          command: |
            apk update --no-progress && apk --no-progress add ca-certificates bash
            nix-env -f nixpkgs.nix -iA stack
      - run:
          name: Compute cache key
          command: |
            find . -name "*.cabal" -o -name "stack.yaml" -o -name "*.nix" -type f | sort | xargs cat > /tmp/stack-deps
      - restore_cache:
          keys:
            - HaskellR-stack-dependencies-0-{{ arch }}-{{ checksum "/tmp/stack-deps" }}
      - run:
          name: Build dependencies
          command: |
            nix-shell --run 'stack --no-terminal build --only-snapshot --prefetch --no-haddock --test --bench --jobs=1 --system-ghc'
      - save_cache:
          key: HaskellR-stack-dependencies-1-{{ arch }}-{{ checksum "/tmp/stack-deps" }}
          paths:
            - ~/.stack
      - run:
          name: Build project
          command: |
            nix-shell --run 'stack --no-terminal --nix build --pedantic --test --bench --no-run-tests --no-run-benchmarks --system-ghc'
      - run:
          name: Test
          command: |
            nix-shell --run 'stack --nix --no-terminal test --system-ghc'
  build-osx-brew:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run:
          name: prepare system
          command: |
            mkdir -p ~/.local/bin
            curl -Lk https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 -C ~/.local/bin
      - run:
          name: install software
          command: |
            brew update
            brew install pkg-config
            brew install --force r zeromq
            pip install ipython==5.5.0
      - run:
          name: install package
          command: |
            ~/.local/bin/stack setup
            ~/.local/bin/stack --no-terminal -j2 build --only-snapshot --prefetch --test --bench
      - run:
          name: test
          command: LC_ALL=en_US.UTF-8 ~/.local/bin/stack --no-terminal -j2 build --pedantic
  build-osx-nix:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run:
          name: Install Nix
          command: |
            curl https://nixos.org/nix/install | sh
      - run:
          name: Compute cache key
          command: |
            find . -name "*.cabal" -o -name "stack.yaml" -o -name "*.nix" -type f | sort | xargs cat > /tmp/stack-deps
      - restore_cache:
          keys:
            - HaskellR-stack-dependencies-0-{{ arch }}-{{ checksum "/tmp/stack-deps" }}
      - run:
          name: Build dependencies
          shell: /bin/bash -eilo pipefail
          command: |
            nix-env -f nixpkgs.nix -iA stack
            export LC_ALL="en_US.UTF-8"
            nix-shell --run 'stack --no-terminal build --only-snapshot --prefetch --no-haddock --test --bench --jobs=1'
      - save_cache:
          key: HaskellR-stack-dependencies-1-{{ arch }}-{{ checksum "/tmp/stack-deps" }}
          paths:
            - ~/.stack
      - run:
          name: Build project
          shell: /bin/bash -eilo pipefail
          command: |
            export LC_ALL="en_US.UTF-8"
            nix-shell --run 'stack --no-terminal build --pedantic'

workflows:
  version: 2
  build:
    jobs:
      - build-linux-nix
      - build-osx-brew
      - build-osx-nix
  publish:
    jobs:
      - publish:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
